export const ROOM_SET_DISPLAY_STATUS = "ROOM_SET_DISPLAY_STATUS";
export const PLAYER_LEAVE_ROOM = "PLAYER_LEAVE_ROOM";
export const PLAYER_SET_USERNAME = "PLAYER_SET_USERNAME";
export const RESET_STORE = "RESET_STORE";